### ISSUE TITLE
Ретвиты в ответах твитов

### ISSUE THREAD

**Issue by dustyo-O** [volchata/pepo_server#47]
При запросе твитов, получать информацию о том, ретвитил ли текущий пользователь данный твит. Для этого, смотрим в твитах пользователя - нет ли у него твитов с текущих в extras

**Comment by a-lexxx** [comment]
Это уже есть и должно функционировать.
Поле retweet:true означает, что пользователя уже ретвитил этот твит

**Comment by dustyo-O** [comment]
это есть и работает, спасибо
